### ISSUE TITLE
Live preview redirects to login page

### ISSUE THREAD

**Issue by TyMick** [creativetimofficial/material-dashboard-react-nodejs#6]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

I can view the dashboard in the [live preview](https://www.creative-tim.com/live/material-dashboard-react-nodejs).

# Current Behavior

https://www.creative-tim.com/live/material-dashboard-react-nodejs flashes the dashboard briefly and then goes to the login page without changing the URL. The dashboard button on this page, which links to https://www.ctim.udevoffice.com/demos/material-free/admin/dashboard, flashes the dashboard briefly again and returns to the login page, all without changing the URL in the browser.

https://www.creative-tim.com/live/material-dashboard-react-nodejs/dashboard is a 404 error.

**Comment by kaazkoo** [comment]
I have the same problem.
What was the solution?

**Comment by TyMick** [comment]
@kaazkoo Never got a solution. ¯\\\_(ツ)_/¯ They've never responded to a single issue on this repo, looks like. I guess they don't use GitHub for collaboration, just as a place to toss their code so they can call it "open source". Oh well.

**Comment by kaazkoo** [comment]
@tywmick

Given that it's now over a year you asked, it may not be relevant for you anymore but, I thought I'd provide you closure and tell you how I fixed it :-)

Not sure what may be the root cause, update or else. I fixed it by modifying the root folder app.js
The issue is linked to the sessions handling with the Redis server. The Redis server wasn't registering ANY sessions. And it seems to have been omitted - or the original implementation logic doesn't work anymore. Any how... 

First you need a client to exchange with the Redis server -- Squeeze this CONST between cookieParser and session

> const redis = require('redis');

and under CONST RedisStore add

> const redisClient = redis.createClient();

get rid of this line --> const redisStore = new RedisStore(redisStoreConfig);
and implement it like this instead, so that redis stores the client session not the config.

app.use(
  session({
    store: new RedisStore({ client: redisClient }),

Works perfectly now. 

JF

**Comment by Lyba97** [comment]
@kaazkoo Hi. I just faced the same problem and read the solution you provided above but it does not work on my end. Did you face any issues after that with this dashboard? Please share any solution if you know.

Thank you in advance 
Lyba
